[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
pumpnotdump = "D5HsjjMSrCJyEF1aUuionRsx7MXfKEFWtmSnAN3cQBvB"

[programs.devnet]
pumpnotdump = "D5HsjjMSrCJyEF1aUuionRsx7MXfKEFWtmSnAN3cQBvB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/skipper-wallet.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
